package AWSRevisionProgramme;

public final class AWSAllQuestions {
    public static final Question[] CLOUD_COMPUTING_QUESTIONS = { new Question("What does a server consist of?",
            "CPU, RAM (memory), Data, Database, network (routers, switch, DNS server)."),
            new Question("What are 5 characteristics of cloud computing?",
                    "On-demand self service; broad network access; multi-tenancy and resource pooling; rapid elasticity and scaling; measured service (only pay for what you use)."),
            new Question(
                    "Define IaaS and give an example.", "Infrastructure as a Service, e.g. EC2."),
            new Question("Define PaaS and give an example.",
                    "Platform as a Service, e.g. Elastic Beanstalk."),
            new Question("Define SaaS and give an example.", "Software as as Service, e.g. Rekognition."),
            new Question("What are the pricing fundamentals for the cloud?",
                    "Compute, storage and data LEAVING the cloud."),
            new Question("What is a region?", "A cluster of data centres."),
            new Question("How many AZs are in a region?", "Between 3 and 6."),
            new Question("Which services are global?", "IAM, Route53, CloudFront, WAF."),
            new Question("Who is broadly responsible for what in the shared responsibility model?",
                    "Customer is responsible for security IN the cloud; AWS is responsible for security OF the cloud.") };
    public static final Question[] IAM_QUESTIONS = {
            new Question("In IAM, what is a policy?",
                    "A JSON document that defines what users are allowed to do."),
            new Question("What is an inline policy?",
                    "A policy attached only to a user (i.e. not inherited from a group)."),
            new Question("What are the three ways to access AWS?", "AWS Manegement Console, CLI and SDK."),
            new Question("What is CloudShell?", "A terminal in the AWS cloud."),
            new Question("What can you use to audit permissions for your users/services?",
                    "IAM Credentials Report and IAM Last Accessed."), };
    public static final Question[] EC2_QUESTIONS = { new Question("What is the EC2 user data script?",
            "Use it to bootstrap an EC2 instance by automating boot up tasks like installing updates or downloading files."),
            new Question("What happens with IP addresses when you stop and restart an EC2 instance?",
                    "The public IP address might change, but the private one will always stay the same."),
            new Question("What are the 4 types of EC2 instance?",
                    "General purpose, compute optimised, memory optimised, storage optimised."),
            new Question("What is a general purpose EC2 instance good for?",
                    "Good balance between compute, memory and networking."),
            new Question("What is a compute optimised EC2 instance good for?",
                    "Tasks that require high performance."),
            new Question("What is a memory optimised EC2 instance good for?",
                    "Procesing large data sets in memory."),
            new Question("What is a storage optimised EC2 instance good for?",
                    "Accessing data sets on local storage."),
            new Question("What is a security group?",
                    "A firewall on an EC2 instance. They control how traffic is allowed in and out of EC2 instances with ALLOW rules."),
            new Question("What is SSH for?", "Controlling a remote machine from the command line."),
            new Question("What alternative is there to SSHing into your EC2 instance?",
                    "Using EC2 Instance Connect."),
            new Question("Which EC2 instance purchase option is best for short-term, uninterrupted workflows?",
                    "On-demand."),
            new Question("Which EC2 instance purchase option is best for steady-state usage app, e.g. a database?",
                    "Reserved instance."),
            new Question("Which EC2 instance purchase option is best for long-term use?",
                    "Savings plans (so you can benefit from a discount)."),
            new Question("Which EC2 instance purchase option is best for workloads that are resilient to failure?",
                    "Spot instance - up to 90% discount but could lose at any time."),
            new Question("Which EC2 instance purchase option is best for meeting compliance?",
                    "Dedicated host - this is a physical server just for you and you can control everything about the phyiscal server, including where the instances are placed on it."),
            new Question(
                    "Which EC2 instance purchase option is best if you want a physical server for a single customer account?",
                    "Dedicated instance."),
            new Question(
                    "What EC2 instance purchase option is best for short, uninterrupted workloads that need to be in a specific AZ?",
                    "Capacity reservations."),
            new Question("What is an EBS volume?",
                    "A network drive you can attach to instances to persist data."),
            new Question("What are some limitations of EBS Volumes?",
                    "They can only be mounted to one instance at a time; they are bound to a specific AZ."),
            new Question(
                    "What is the default behaviour of an EBS volume on the root storage when an EC2 instance is terminated?",
                    "The 'delete on termination' option is ticked, meaning the the EBS volume gets deleted."),
            new Question(
                    "What do you have to keep in mind about the EBS volume and the EC2 instance you want to attach it to?",
                    "They have to be in the same AZ."),
            new Question("What is a snapshot?",
                    "A backup of your EBS volume at a particular point in time."),
            new Question("Can you copy an EBS snapshot across AZ or regions?", "Yes"),
            new Question("How can you control what happens to deleted snapshots?", "With retention rules."),
            new Question("What is an AMI?",
                    "Amazon Machine Image - this powers the EC2 instances. It's used to start the instance and it means the boot up is faster."),
            new Question("Where can you get AMIs?",
                    "You can use AMIs provided by Amazon, you can make your own, or get one from AWS Marketplace."),
            new Question("What is an EC2 Image Builder?",
                    "EC2 Image Builders automate the creation of VMs or container images. The Image Builder creates a Builder EC2 instance, which builds components and customises software. That then creates an AMI, which creates a test EC2 instance. Then the AMI is distributed."),
            new Question("What is the pricing model for EC2 image builder?",
                    "Image builder is free; you just pay for the EC2 instances and AMI."),
            new Question("What is the EC2 Instance Store?",
                    "A hard drive that's attached to the physical server that houses the EC2 instance."),
            new Question("What are some pros and cons of an EC2 Instance Store?",
                    "High-performance storage (better than EBS volume); better I/O performance and throughput; if you terminate the EC2 instance the storage is lost."),
            new Question("What is an EC2 Instance Store good for?", "Buffer/cache/temporary content."),
            new Question("What is EFS?",
                    "Elastic File System - a managed Network File System (NFS) that can be mounted on hundreds of EC2 instances at a time."),
            new Question("Name one pro and one con of EFS.",
                    "Works in multiple AZs; only works with Linux EC2 instances."),
            new Question("How do I move an EBS volume from one AZ to another?",
                    "Create a snapshot and use that to restore it. This is a copy - not an in-sync replica."),
            new Question("True or false: Whatever is on the EFS drive is shared by everything mounted to it.",
                    "True"),
            new Question("What is EFS-IA?", "Elastic File System Infrequent Access - cost optimised."),
            new Question("What is FSx?",
                    "A managed service to get third-party high-performance file systems on AWS"),
            new Question("How can I access the Windows file server over SMB?",
                    "Using FSx for Windows File Server."),
            new Question(
                    "How can I achieve high-performance, scalable storage for HPC (high performance computing) on Linux?",
                    "FSx for Lustre.") };
    public static final Question[] ELB_ASG_QUESTIONS = {
            new Question("What does scalability mean?", "That an app/system can adapt to greater loads."),
            new Question("What is vertical scaling?", "Scaling up - increasing the size of the instance."),
            new Question("What is a common use case for vertical scaling (as opposed to horizontal scaling)?",
                    "Non-distributed systems like databases."),
            new Question("What is horizontal scaling?",
                    "Scaling out - increasing the number of instances."),
            new Question("How do you achieve horizontal scaling in EC2?", "With ASGs and/or ELBs."),
            new Question("What can you imply from a system that employs horizontal scaling?",
                    "Distributed systems - a network of independent computers that work together as a single unit."),
            new Question("What is high availability and why aim for this?",
                    "Running your app/system in at least 2 AZs to survive a data centre loss."),
            new Question("What is elasticity?", "Auto-scaling."),
            new Question("What are load balancers?",
                    "Servers that forward internet traffic to multiple servers (EC2 instances)."),
            new Question("Can you use ELBs across multiple AZs?", "Yes."),
            new Question("Describe an Application Load Balancer (ALB).",
                    "This is HTTP/HTTPS/gRPC - layer 7. It has a static DNS (URL)."),
            new Question("Describe a Network Load Balancer (NLB).",
                    "TCP/UDP protocols (layer 4). Ultra high performance. Static IP through Elastic IP."),
            new Question("Describe a Gateway Load Balancer (GLB).",
                    "GENEVE Protocol on IP packets (layer 3). Route traffic to firewalls that you manage on EC2 instances. Intrusion detection."),
            new Question("What is an ASG?",
                    "Auto Scaling Group - scales in and out automatically to match load, thus saving costs. Works hand in hand with load balancers."),
            new Question("In ASG, what is simple/step scaling?", "Define a trigger to manage scaling."),
            new Question("In ASG, what is target tracking scaling?", "e.g. define an average CPU."),
            new Question("In ASG, what is scheduled scaling?", "Anticipate based on known patterns."),
            new Question("In ASG, what is predictive scaling?", "Use ML to predict needs.") };
    public static final Question[] S3_QUESTIONS = {
            new Question("What is the geographical scope for S3 buckets?",
                    "Buckets are defined at the region level."),
            new Question("What are the two ways to manage security in S3?",
                    "IAM policies and bucket policies."),
            new Question("What do you need to ensure to be able to host a static website in S3?",
                    "Public reads are enabled on the bucket."),
            new Question("What happens if you upload an object to the bucket with the same name as an existing object?",
                    "A new version of that object will be created."),
            new Question("If versioning is not enabled, what happens when you delete an object in S3?",
                    "It's not actually deleted - it just adds a delete marker."),
            new Question("What are the two types of bucket replication?",
                    "Cross region replication (CRR) and Same region replication (SRR)."),
            new Question("What are the use cases for cross region replication in S3?",
                    "Compliance, lower latency access, replication across accounts."),
            new Question("What are the uses cases for same region replication is S3?",
                    "Log aggregation, live replication between prod and test accounts."),
            new Question("What is standard (general purpose) S3 storage good for?",
                    "Big data analytics, mobile and gaming apps, content distribution. (High availability, low latency, high throughput.)"),
            new Question("What is standard-infrequent access S3 storage class good for?",
                    "Disaster recovery, backups. (Cost on retrieval. For data that is less frequently accessed but needs to be fast.)"),
            new Question("What is One Zone Infrequent Access S3 storage class good for?",
                    "Secondary backups of on-prem data, or data you can recreate. (Cost on retrieval; high durability in a single AZ.)"),
            new Question("What is Glacier Instant Retrieval S3 storage class good for?",
                    "Data that needs to be accessed once a quarter. (Min storage duraton of 90 days. Data accessed in milliseconds.)"),
            new Question("What is Glacier Flexible Retrieval S3 storage class good for?",
                    "Data that you don't need instantly - can take up to 12 hours. Min storage duration 90 days."),
            new Question("What is Glacier Deep Archive in S3 storage good for?",
                    "Long-term storage. Takes 12-48 hours to retrieve data. Min storage duration 180 days."),
            new Question("What is intelligent tiering in S3?",
                    "Pay a small fee for items to be moved automatically based on usage."),
            new Question("What does durability refer to in S3?",
                    "How likely it is for an object to be lost."),
            new Question("What is S3 Express one zone?", "A high-performance single AZ storage class."),
            new Question("What are the use cases for the S3 Express One Zone storage class?",
                    "Latency-sensitive apps; data-insensitive apps; AI and ML training; financial modelling; media procesing; HPC."),
            new Question("What's the deal with encryption in S3?",
                    "S3 buckets have server-side encryption by default, whenever you create a bucket or upload an object."),
            new Question("What is IAM access analyser for S3?",
                    "A tool that evaluates S3 bucket policies, ACLs, etc and tells you which buckets are publicly accessible."),
            new Question("What was AWS Snowball?",
                    "A (now discontinued) portable device to collect and process data at the edge."),
            new Question("What is AWS Storage Gateway?",
                    "A bridge between on-prem data and cloud data in AWS."),
            new Question("What are the use cases for AWS Storage Gateway?",
                    "Disaster recovery, backup and storage, tiered storage.") };
    public static final Question[] DATABASE_ANALYTICS_QUESTIONS = {
            new Question("What are some example formats of NoSQL databases?",
                    "key-value, document, graph, in-memory, search."),
            new Question("What are some benefits of NoSQL databases?",
                    "They are flexible, scalable, high-performance, high functional."),
            new Question("What is RDS?",
                    "Relational Database Service - a managed database service for DBs that use SQL."),
            new Question("What is Aurora?",
                    "An AWS DB. Cloud-optimised - better performance than PostgrSQL or MySQL. Costs more than RDS but is more efficient. It also has a serverless option."),
            new Question("What is AWS Secrets Manager?", "Used to manage credentials."),
            new Question("How might I restore my DB?", "Take a snapshot."),
            new Question("What is a read replica?",
                    "Replicas of your database so your app can carry out read operations on up to 15 replicas. This balances the load as your app/DB scales."),
            new Question("How can you set up a failover DB?", "Have a replication in a different AZ."),
            new Question("What are benefits of multi-region read replicas?",
                    "Good for disaster recovery; less latency when reading from local DBs."),
            new Question("What is ElastiCache?", "A DB for a managed Redis or Memcached DB."),
            new Question("What is a cache?", "In-memory database with high performance and low latency."),
            new Question("Trigger word: in-memory database >>", "ElastiCache"),
            new Question("What is DynamoDB?",
                    "A fully managed, highly available NoSQL DB with replication across 3 AZs - so low latency."),
            new Question("What is DynamoDB accelerator (DAX)?",
                    "An in-memory cache specifically for DynamoDB."),
            new Question("What are DynamoDB Global tables?",
                    "A way to achieve 2-way replication in different regions. You can read and write to both - this is active-active replication."),
            new Question("Which DB service would you choose for OLTP (Online Transaction Processing)?",
                    "RDS."),
            new Question("When would I use Redshift?", "For analytics and data warehousing."),
            new Question("What would I use for Online Analytical Processing (OLAP)?", "Redshift"),
            new Question("What would I use for reporting, dashboarding, or real-time analytics?",
                    "Redshift serverless."),
            new Question("What is EMR?",
                    "Elastic Map Reduce - used to create a Hadoop cluster for big data analysis."),
            new Question("What is Athena?",
                    "A query service that uses SQL to perform analytics against S3 objects."),
            new Question("What would you use to analyse data in S3?", "Athena."),
            new Question("What is QuickSight?", "A serverless, ML-powered service to create dashboards."),
            new Question("What is DocumentDB?",
                    "An AWS implementation of MongoDB. It's fully managed, highly available, and has replication across 3 AZs."),
            new Question("What is Neptune?", "A fully managed graph database."),
            new Question("What is Timestream?",
                    "A fully managed, fast, scalable, serverless time series database."),
            new Question("What is Amazon Managed Blockchain?",
                    "A managed service to join public blockchain networks and create scalable private networks within AWS."),
            new Question("What would I use to extract, transform and load data for analytics?",
                    "Glue (a managed ETL service)."),
            new Question("What is DMS?",
                    "Data Migration Service - quickly and securely migrate DBs to AWS.") };
    public static final Question[] OTHER_COMPUTE_QUESTIONS = {
            new Question("What is ECR?", "Elastic Container Registry - a private Docker repository."),
            new Question("What is the ECS used for?",
                    "Elastic Container Service - used to launch Docker containers on AWS."),
            new Question("What is Fargate?", "A serverless way to launch Docker containers on AWS."),
            new Question(
                    "What do I choose if I want to launch Docker containers on AWS but don't want to manage the EC2 instances myself?",
                    "Fargate."),
            new Question(
                    "Which service will start/stop Docker containers on EC2 instances that you provision and maintain yourself?",
                    "ECS."),
            new Question("What is EKS?",
                    "Elastic Kubernetes Service - launch managed Kubernetes clusters on AWS."),
            new Question("What is Lambda?", "It lets you run functions in the cloud."),
            new Question("What should I use if I need to run a short executing function on demand?",
                    "Lambda."),
            new Question("How does Lambda pricing work?",
                    "It's based on calls and duration. Very cheap so very popular."),
            new Question("What would I use if I want to create and publish APIs?", "API Gateway."),
            new Question("Trigger wording: Serverless API >>", "API Gateway + Lambda"),
            new Question("What is a batch job?", "A job with a start and an end."),
            new Question("What is AWS Batch?", "A fully managed batch processing service."),
            new Question("How does Batch work?",
                    "It dynamically launches EC2 instances or spot instances to meet the load required for batch jobs."),
            new Question("How are batch jobs defined and run?",
                    "Defined as Docker images and run on ECS, EKS or Fargate."),
            new Question("What's the time limit for Lambda functions?", "15 mins."),
            new Question("What is Lightsail?",
                    "A simpler alternative to all the cloud stuff - good for people with little cloud experience.") };
    public static final Question[] DEPLOYMENTS_INFRA_AT_SCALE_QUESTIONS = {
            new Question("Give an example of IaC.", "CloudFormation."),
            new Question("What is CloudFormation?",
                    "IaC - a declarative way of outlining your AWS Infrastructure for any resources."),
            new Question(
                    "What would I use when I need to repeat an architecture in different environments, different regions or different AWS accounts?",
                    "CloudFormation."),
            new Question("What is CDK?",
                    "Cloud Development Kit - compiles code written in familiar programming languages to a CloudFormation template."),
            new Question("What is Elastic Beanstalk?", "A PaaS - dev-centric way of deploying an app."),
            new Question("What do you use if you want to upload code and let AWS handle the deployment?",
                    "Elastic Beanstalk."),
            new Question("Does Elastic Beanstalk have health monitoring?", "Yes."),
            new Question("What is the difference between CodeDeploy and Beanstalk?",
                    "Beanstalk also handles load balancing and scaling, whereas CodeDeploy is just the deployment."),
            new Question("What is CodeDeploy?", "A way to deploy your app automatically."),
            new Question("What is CodeCommit?", "AWS version of GitHub."),
            new Question("What is CodeBuild?", "A service that lets you build your code in the cloud."),
            new Question("How does CodeBuild work?",
                    "It retrieves the code form CodeCommit, runs a script, builds the code, then creates a ready-to-deploy artifact."),
            new Question("What is CodePipeline?", "A CI/CD pipeline."),
            new Question("What is CodeArtifact?",
                    "Artifact management for software development, i.e. storing and retrieving dependencies."),
            new Question("What is SSM?",
                    "Systems Manager - helps you manage your fleet of EC2 instances and on-prem systems at scale."),
            new Question("What are some features of SSM?",
                    "Automatic patching for enhanced compliance; run commands across an entire fleet of servers; store parameter configurations in the SSM parameter store."),
            new Question("What is SSM Session Manager?",
                    "Lets you start a secure shell on your EC2 instance without needing SSH access/keys."),
            new Question(
                    "How can I start a secure shell on my EC2/on-prem servers without needing SSH access or SSH keys?",
                    "SSM Session Manager."),
            new Question("What is the SSM Parameter Store?",
                    "Secure storage for config and secrets. Serverless, scalable, durable, easy SDK."),
            new Question("Trigger words: a way to patch your fleet >>", "Systems Manager"),
            new Question("Trigger words: run commands consistently across all servers >>",
                    "Systems Manager") };
    public static final Question[] GLOBAL_INFR_QUESTIONS = {
            new Question("What is Route53?", "A managed DNS (Domain Name System)."),
            new Question("What DNS record is used to map a website to an IPv4 address?", "An A record."),
            new Question("What DNS record is used to map a website to an IPv6 address?",
                    "A quadruple A record."),
            new Question("What DNS record is used to map a hostname to another hostname?",
                    "A CNAME record."),
            new Question("What DNS record is used to map a hostname to an AWS record?", "An alias record."),
            new Question("Which Route53 routing policy doesn't involve health checks?",
                    "Simple routing policy."),
            new Question("Describe a Route53 weighted routing policy.",
                    "It lets you distribute traffic across different EC2 instances (a kind of load balancing)."),
            new Question("In Route53, what is a latency routing policy?",
                    "It looks where the user is located and redirects them to the closest server."),
            new Question("In Route53, what is a failover routing policy?",
                    "This is for disaster recovery - if the health check on the primary fails, it is redirected to the failover one."),
            new Question("What is CloudFront?",
                    "A Content Delivery Network (CDN). It decreases latency by caching the content of your website at different edge locations."),
            new Question("What's the difference between CloudFront and S3 CRR?",
                    "CloudFront uses the global edge network and files are cached for a set time. S3 CRR has to be set up for each region and files are updated in near real time."),
            new Question("To improve latency for static content would you choose CloudFront or S3 CRR?",
                    "CloudFront."),
            new Question("To improve latency for dynamic content would you choose CloudFront or S3 CRR?",
                    "CRR."),
            new Question("What is S3 Transfer Acceleration and how does it work?",
                    "It's used to speed up uploads into an S3 bucket by uploading to an edge location closer to the user first then using a faster connection to the S3 bucket."),
            new Question("What is AWS Global Accelerator?",
                    "This routes requests through the internal network which optimises the route to your app. There is a private connection from the edge location to the app."),
            new Question("Does Global Accelerator cache content?", "No."),
            new Question("What are AWS Outposts?",
                    "Server racks that let you build your own apps on-prem just like in the cloud."),
            new Question(
                    "What are AWS WaveLength zones?",
                    "Infrastructure deployments embedded within the telecoms providers' data centres at the edge of 5G networks."),
            new Question("Trigger word: 5G >>", "WaveLength."),
            new Question("What is a Local Zone for?",
                    "You place compute, storage, DB and other AWS services closer to end users to run latency-sensitive apps."),
            new Question("Give 3 features of Single Region Single AZ architecture.",
                    "Low availability; easy to set up; low latency only for users in that AZ."),
            new Question("Give 3 features of a single region, multi AZ architecture.",
                    "High availability; moderately easy to set up; latency good for users in that region."),
            new Question("Describe multi region, active-passive architecture.",
                    "Latency good for reads but not for writes; slightly more difficult to set up than single region options."),
            new Question("Describe multi region, active-active architecture.",
                    "All regions actively serve user traffic simultaneously, so latency good for reads and writes. Most difficult to set up and maintain.") };
    public static final Question[] CLOUD_INTEGRATIONS_QUESTIONS = {
            new Question("What is another term for app to app communication?",
                    "Synchronous communication."),
            new Question("What is another term for app to queue to app communciation?",
                    "Asynchronous communication."),
            new Question("which communication type (sync or async) is better for sudden spikes in traffic?",
                    "Async."),
            new Question("What is SQS?",
                    "Simple Queue Service - producers send things to the queue. Consumers poll the queue, process the thing then delete the message."),
            new Question("Trigger word: decouple >>", "SQS"),
            new Question("What is Kinesis for?",
                    "Real-time big data streaming. Ingest data at scale from thousands of sources."),
            new Question("What would I use if I wanted to ingest data at scale from thousands of sources?",
                    "Kinesis."),
            new Question("What is SNS?",
                    "Simple Notification System - a way to send one message to many receivers. An event publisher sends a message to an SNS topic, and many event subscribers can listen to the notifications."),
            new Question("Which service follows the pub/sub model?", "SNS - Simple Notification Service."),
            new Question("Trigger words: notification/publishers/subscriptions >>", "SNS"),
            new Question("What is Amazon MQ?", "A message broker service for RabbitMQ and ActiveMQ."),
            new Question("When would I use Amazon MQ?",
                    "If I am migrating to the cloud and need to use protocols like MDTT, AMQP, STOMP etc.") };
    public static final Question[] CLOUD_MONITORING_QUESTIONS = {
            new Question("What is CloudWatch?", "It provides metrics for every service in AWS."),
            new Question("What restriction is there for the billing metric in CloudWatch?",
                    "It's only available in us-east-I-region."),
            new Question("What are CloudWatch alarms for?",
                    "They trigger notifications and/or actions (like autoscaling, stop/start/reboot/recover an EC2 instances, send notification to SNS topic) for any metric."),
            new Question("What is CloudWatch Logs for?", "Collecting log files."),
            new Question("What are some services that you can collect CloudWatch Logs from?",
                    "Elastic Beanstalk, ECS, Lambda, CloudTrail, Route53."),
            new Question("What is EventBridge for?",
                    "It lets you raect to events happening in your AWS account. You can create CRON jobs or trigger something based on an event."),
            new Question("What is X-ray for?",
                    "Tracing and getting a visual analysis of your apps to aid in debugging distributed services."),
            new Question("What is the AWS Health Dashboard?",
                    "Somewhere where you can see service history (all regions and all services) and your account health (things only relevant to your account).") };
    public static final Question[] VPC_NETWORKING_QUESTIONS = {
            new Question("What is Elastic IP for?",
                    "It lets you attach fixed IPv4 addresses to EC2 instances."),
            new Question("What is VPC?",
                    "Virtual Private Cloud - a private network to deploy your resources."),
            new Question("How are VPCs scoped?", "A VPC is linked to a specific region."),
            new Question("Describe subnets.",
                    "Subnets are used to partition your network within a VPC. They can be public or private."),
            new Question("How are subnets scoped?", "Each subnet is associated with an AZ."),
            new Question("What are route tables used for?",
                    "In a VPC, to define access to the internet and access between subnets."),
            new Question("What is the CIDR range?", "The range of IP addresses allowed in the VPC."),
            new Question("What is an internet gateway?",
                    "It allows public subnets to access the internet."),
            new Question("What is a NAT Gateway?",
                    "A Network Address Translation Gateway - placed in a public subnet with a route to the private subnet to let the private one connect to the internet."),
            new Question("What VPC is used when we create an EC2 instance?",
                    "There is a default VPC which the network defaults to."),
            new Question("What determines the private IP in an EC2 instances?",
                    "The subnet that is being used in the VPC."),
            new Question("What is a NACL?",
                    "Network Access Control List - a firewall which controls traffic to and from a subnet with ALLOW and DENY rules."),
            new Question("What level does the NACL operate at?", "The subnet level."),
            new Question("Which type of firewall only has ALLOW rules?", "A security group."),
            new Question("Which type of firewall has ALLOW and DENY rules?", "NACL."),
            new Question("What level does a security group operate at?", "EC2 instance level."),
            new Question(
                    "Which type of firewall is stateful (return traffic is automatically allowed regardless of rules)?",
                    "Security Group."),
            new Question("Which type of firewall is stateless (return traffic must be explicitly allowed by rules)?",
                    "NACL."),
            new Question("What is a VPC Flow Log?", "A log of all traffic going through your interfaces."),
            new Question("What would I use to monitor and troubleshoot connectivity issues in my VPC?",
                    "VPC Flow Logs."),
            new Question("What is VPC peering?", "Connecting to VPCs privately using AWS' network."),
            new Question("What are VPC endpoints?",
                    "They let you connect to AWS services using a private network instead of a public network."),
            new Question("What are 2 benefits of VPC endpoints?", "Enhanced security and lower latency."),
            new Question("What sort of VPC endpoint would I use only for S3 or DynamoDB?",
                    "A VPC endpoint gateway."),
            new Question("What sort of VPC endpoint works for all services?", "VPC endpoint interface."),
            new Question("What is PrivateLink?",
                    "The most secure and scalable way to expose a service to thousands of VPCs."),
            new Question(
                    "What would I do if I need to connect my on-prem data centre to my VPC in the cloud very quickly?",
                    "Site to Site VPN (which goes over the public internet)."),
            new Question(
                    "What would I do if I need to connect my on-prem data centre to my VPC in the cloud and I need the connection to be private?",
                    "Direct Connect (DX) - physical connection so takes at least a month and is more expensive."),
            new Question(
                    "With a Site to Site VPN, what do I need to set up on-prem and what do I need to set up on the AWS side?",
                    "On-prem: Customer Gateway (CGW). AWS: Virtual Private Gateway (VGW)"),
            new Question("How do I privately connect into my AWS VPC?", "Using a Client VPN."),
            new Question("What would I use to get transitive peering between thousands of VPC and on-prem systems?",
                    "Transit Gateway."),
            new Question("What sort of connection does a Transit Gateway use?", "Hub-and-spoke (star).") };
    public static final Question[] SECURITY_COMPLIANCE_QUESTIONS = {
            new Question("Whose responsibility is hardware, networking, and managed services?", "AWS."),
            new Question("Whose responsibility is guest OS, firewalls, network config and encrypting app data?",
                    "The customer's."),
            new Question("What types of attack does AWS Shield Standard protect against?",
                    "DDoS and other layer3/layer 4 attacks."),
            new Question("Which service offers 24/7 premium DDoS protection?", "AWS Shield Advanced."),
            new Question("What is WAF?", "Web Application Firewall - a firewall to protect your web apps."),
            new Question("How does WAF protect your web apps?",
                    "It filters requests based on rules that you create/use in a Web Access Control List (ACL)."),
            new Question("What is a Web ACL?",
                    "Web Access Control List - rules to filter requests to your web app."),
            new Question("Which service protects your app against layer 7 (HTTP) attacks?", "WAF."),
            new Question("Where can WAF be deployed?", "On load balancers, API Gateway, CloudFront."),
            new Question(
                    "What would I use to protect my entire VPC from layer 3 to layer 7 attacks in both directions?",
                    "Network Firewall."),
            new Question("What would I use to manage security rules in all accounts in an AWS Organisation?",
                    "Firewall Manager."),
            new Question("Am I allowed to carry out penetration tests on my AWS infrastrucutre?",
                    "Yes - without prior approval."),
            new Question("Am I allowed to carry out DNS zone walking on my AWS infrastructure?", "Never."),
            new Question("Am I allowed to carry out DDoS attacks on my AWS infrastructure?", "Never."),
            new Question(
                    "Am I allowed to carry out port flooding/request flooding/protocol flooding on my AWS infrastructure?",
                    "Never."),
            new Question("How does Key Management Service (KMS) work?",
                    "It's an encryption service - AWS manages the keys and the customer has to define who can access them."),
            new Question("Name 3 services where encryption is automatically enabled",
                    "CloudTrail logs, S3 glacier, Storage Gateway."),
            new Question("What is CloudHSM?",
                    "Hardware Security Module - hardware provisioned by AWS where the customer manages the keys."),
            new Question("What are the four types of keys?",
                    "CMK - customer managed key; AWS-managed key; AWS-owned key; CloudHSM key"),
            new Question("What service do you use to provision, manage and deploy SSL/TLS certificates?",
                    "AWS Certificates Manager (ACM)."),
            new Question("How do the certificates in ACM work?",
                    "They provide in-flight encryption for your website by providing a HTTPS endpoint."),
            new Question("What services can certificates be loaded on to?",
                    "ELB, CloudFront Distributions, APIs on API Gateway."),
            new Question("How do I store secrets in AWS?", "Secrets Manager."),
            new Question("How can I automate the generation of new secrets for rotation?", "Lambda."),
            new Question("How can I prove compliance for internal audits?",
                    "Download Artifacts Reports/Artifacts Agreements."),
            new Question("What is GuardDuty?",
                    "Intelligent threat discovery using ML algorithms to protect your AWS account."),
            new Question("What service provides intelligent threat discovery?", "GuardDuty."),
            new Question("Which service uses ML algorithms to detect anomalies and find threats?",
                    "GuardDuty."),
            new Question("Which service has a dedicated finding for CryptoCurrency attacks?", "GuardDuty."),
            new Question("Which three things does Amazon Inspector run automated security assessments on?",
                    "EC2 instances, container images and lambda functions."),
            new Question(
                    "Which service looks at CVEs and can report its findings to AWS Security Hub/send to Amazon Event Bridge?",
                    "Amazon Inspector."),
            new Question("What service can help with auditing and recording compliance for AWS resources?",
                    "AWS Config."),
            new Question("Which service uses ML/pattern matching to disover and protect sensitive data/PII in AWS?",
                    "Macie."),
            new Question("What is AWS Security Hub?",
                    "A central security tool to manage security across several AWS accounts."),
            new Question("What is a prerequisite for using Security Hub?",
                    "You have to enable the Config Service first."),
            new Question("What is Amazon Detective?",
                    "It analyses, investigates and indentiifes the root cause of security issues or suspicious activities using ML and graphs."),
            new Question("What should I do if I suspect AWS resources are being abused?",
                    "Report to the AWS Abuse Team."),
            new Question("How can I find out which resources are shared externally?",
                    "Using the IAM Access Analyser.") };
    public static final Question[] ML_QUESTIONS = {
            new Question("Which service finds people, objects, text and scenes in images and videos using ML?",
                    "Rekognition."),
            new Question("What would I use to carry out facial analysis/facial search?", "Rekognition."),
            new Question("How do I convert speech to text?", "Transcribe."),
            new Question("What technology does Transcribe use?", "ASR (Automatic Speech Recognition)."),
            new Question("Which service turns text into speech?", "Polly."),
            new Question("Which technology powers Alexa?", "Lex."),
            new Question("Which technology has ASR and natural language understanding?", "Lex."),
            new Question("Which service finds insights and relationships in text?", "Comprehend."),
            new Question(
                    "What would I use if I want to analyse customer emails to find what leads to a positive/negative experience?",
                    "Comprehend."),
            new Question("What technology does Comprehend use?", "NLP - Natural Language Processing."),
            new Question("What is SageMaker for?", "Building AI models."),
            new Question("What is the name of the fully managed document search service powered by ML?",
                    "Kendra."),
            new Question("What would I use to extract answers from within a document?", "Kendra."),
            new Question("Which service (used by Amazon.com) has real-time personalised recommendations?",
                    "Personalise."),
            new Question("Which service extracts text, handwriting and data from scanned documents using AI and ML?",
                    "Textract."),
            new Question("What's the difference between Kendra and Comprehend?",
                    "Kendra is a simple extraction service; Comprehend does analysis.") };
    public static final Question[] ACCOUNT_BILLING_SUPPORT_QUESTIONS = { new Question(
            "What are 3 cost benefits of using an Organization?",
            "Consolidated billing; benefits from aggregated usage (e.g. volume discount); pooling of reserved EC2 instances for optimal savings."),
            new Question("What is an SCP?", "Service Control Policy"), new Question("What is an SCP for?",
                    "Restricting account privileges by whitelisting or blacklisting IAM actions."),
            new Question("What level are SCPs applied to?",
                    "The Operational Unit (OU) level. They do not apply to the master account."),
            new Question("How would I set up and govern a secure and compliant multi-account AWS environment?",
                    "AWS Control Tower"),
            new Question("What is AWS Control Tower?",
                    "A way to set up a multi-account AWS environment. It will create Organizations on your behalf and takes a long time."),
            new Question("What is AWS RAM?",
                    "AWS Resource Access Manager - it lets you share AWS resources that you own with other AWS accounts."),
            new Question("What is AWS Service Catalogue?",
                    "Self-service portal to launch products pre-defined by admins."),
            new Question("What are the 4 pricing models of AWS?",
                    "Pay as you go; save when you reserve; volume-based discounts; pay less as AWS grows."),
            new Question("How does a savings plan work?",
                    "You commit to a certain amount in dollars per hour for 1 or 3 years."),
            new Question("Which compute services can you use with the compute savings plan?",
                    "EC2, Fargate, Lambda."),
            new Question("What is the potential discount when using EC2 savings plan?", "Up to 72%."),
            new Question("What discount can you get with the compute savings plan?",
                    "Up to 66% regardless of family, region or compute options."),
            new Question("What can I use to rightsize my workloads?", "Compute optimiser."),
            new Question("What would I use to estimate costs in the cloud?", "Pricing calculator."),
            new Question("What would I use to track costs in the cloud (x4)?",
                    "Billing dahsboard; cost allocation tags; cost and usage reports; cost explorer."),
            new Question("What would I use to monitor against costs plans?", "Billing alarms; budgets."),
            new Question("What are billing alarms?", "Simple alarms for actual cost, not projected costs."),
            new Question("How do budgets work?",
                    "You set a budget and get an alarm when costs exceed that."),
            new Question("What are the four types of budget?", "Usage, cost, reservation, savings plan."),
            new Question("What service uses ML to detect unusual spends?", "AWS cost anomaly detection."),
            new Question("What is AWS trusted advisor?",
                    "A high level account assessment that analyses your AWS accounts and provides recommendations on cost optimisation, performance, security, fault tolerance, service limits and operational excellence.") };
    public static final Question[] ADVANCED_IDENTITY_QUESTIONS = {
            new Question("How would I create temporary, limited-privileges credentials to access my AWS resources?",
                    "STS - Security Token Service."),
            new Question("What is STS useful for?", "Identity federation or IAM roles."),
            new Question("What is Cognito for?", "Making a user for your apps (alternative to IAM user)."),
            new Question("What is an AD?",
                    "Active Directory - a database of objects like user accounts, computers, printers, file shares, security groups."),
            new Question("What is AWS Managed Microsoft AD?",
                    "It lets you create your own AD in AWS to establish a trust connection with your on-prem AD."),
            new Question("What is the AD connector?", "A directory gateway which redirects to on-prem AD."),
            new Question("What is the Simple AD?",
                    "An AD-compatible managed directory on AWS, but it cannot be joined with on-prem AD."),
            new Question("What is the AWS IAM Identity Centre?",
                    "Successor to SSO. One login for all AWS accounts in an organisation.") };
    public static final Question[] OTHER_SERVICES_QUESTIONS = { new Question("What is WorkSpaces?",
            "A Desktop as a Service (DaaS) solution to provision Windows or Linux desktops."),
            new Question("What is AppStream 2.0?", "A desktop application streaming service."),
            new Question("What is IoT Core?",
                    "It lets you connect IoT devices to the cloud so your apps can communicate with your devices even when not connected."),
            new Question("What is AppSync?",
                    "It uses GraphQL to store and sync data across mobile and web apps in real time."),
            new Question("What is Amplify?",
                    "A set of tools and services that helps you develop and deploy scalable full stack web and mobile apps."),
            new Question("What is AWS Infrastructure Composer?",
                    "It generates IaC using CloudFormation. Can be used to design and build serverless apps quickly."),
            new Question("What is Device Farm?",
                    "A service that lets you test your apps against desktop browsers, real mobile devices and tablets."),
            new Question("What is AWS Backup?",
                    "A fully managed backup service to manage and automate backups, either on-demand or scheduled."),
            new Question("List 4 disaster recovery strategies.",
                    "Backup and restore (least expensive); pilot light - core functions of the app; warm standby - full version of the app at minimum size; multi-site/hot-site - full version of the app at full size."),
            new Question("What is AWS DRS?",
                    "Elastic Disaster Recovery - continuous block-level replication for your servers for disaster recovery."),
            new Question("How can I move large amounts of data from on-prem to AWS?", "With DataSync."),
            new Question("What are the 7 Rs of cloud migration strategies?",
                    "Retire, Retain, Relocate, Rehost, Replatform, Repurchase, Refactor/Rearchitect."),
            new Question("What solution helps build a data-driven case for migration?",
                    "AWS Migration Evaluator."),
            new Question(
                    "What is the name of the central location to collect servers and apps inventory data for migration?",
                    "Migration Hub."),
            new Question("How would I run fault injection experiments on AWS workloads?",
                    "AWS FIS - Fault Injection Simulator"),
            new Question("What is AWS FIS based on?",
                    "Chaos Engineering - stress an app to see how it responds."),
            new Question("How can I build serverless visual workflows to orchestrate my Lambda functions?",
                    "With Step Functions"),
            new Question(
                    "What is the fully managed service that lets you control satellite comms, process data and scale satellite operations by providing a global network of satellite ground stations near AWS regions?",
                    "Ground Station."),
            new Question("What is AWS Pinpoint?", "A scalable, 2-way marketing comms service.") };
    public static final Question[] ARCHITECTURE_ECOSYSTEM_QUESTIONS = { new Question(
            "What are five best practice design principles?",
            "Scalability, disposable resources, automation, loose coupling, services not servers."),
            new Question("What are the six pillars?",
                    "Operational excellence; security; reliability; performance efficiency; cost optimisation; sustainability."),
            new Question("What can I use to review my architecture against the 6 pillars framework?",
                    "AWS Well-Architected Tool."),
            new Question(
                    "How can I track, measure, review and forecast the carbon emissions generated from my AWS usage?",
                    "AWS Custom Carbon Footprint Tool."),
            new Question("How can I plan then execute a plan for digital transformation?",
                    "With the AWS Cloud Adoption Framework (CAF)."),
            new Question("What are the six perspectives in the Cloud Adoption Framework?",
                    "Business, People, Governance, Platform, Security and Operations."),
            new Question("What are the four CAF transformation DOMAINS?",
                    "Technology, process, organisation and product."),
            new Question("What are the four CAF transformation PHASES?", "Envision, align, launch, scale."),
            new Question(
                    "What is the name for the process of matching instance types and sizes to your workload needs at the lowest possible cost?",
                    "Right sizing."),
            new Question("When should you do right sizing?",
                    "Before migration and continuously after cloud onboarding."),
            new Question("What is the AWS Professional Services Organisation?",
                    "A global team of experts."),
            new Question("What types of partners are there in the AWS Partner Network (x3)?",
                    "Technology partners, consulting partners and training partners."),
            new Question("How can I find professional help for my AWS projects?", "AWS IQ."),
            new Question("What is AWS re:Post?", "A Q&A forum."),
            new Question("Where can I find the most frequent questions/requests?", "AWS Knowledge Centre"),
            new Question("What service provides infrastructure and application support on AWS?",
                    "AWS Managed Services (AMS).") };
    public static final Question[] FOLLOW_UP_QUESTIONS = {
            new Question("What is block level storage?",
                    "It splits data into evenly sized, independent chunks called blocks."),
            new Question("What is an advantage of block level storage?",
                    "It speeds up read and write tasks."),
            new Question("What tasks is block level storage good for? (x2)", "DBs or booting VMs."),
            new Question("Which 2 AWS services offer block level storage?", "EBS and EC2 instance store."),
            new Question("Which AWS service offers object storage?", "S3"),
            new Question("Which 2 AWS services offer file storage?", "EFS and FSx."),
            new Question("Can EFS be used directly with on-premises systems?", "Yes."),
            new Question("What is an instance store?", "A hard drive attached to the physical server."),
            new Question("What is an instance store good for and why?",
                    "Buffer/cache/temporary content - because it's high-performance but lost if the EC2 instance is terminated."),
            new Question("What are some required fields in a JSON IAM policy?",
                    "Version, Statement, Effect, Principal (in resource-based policies), Resource/NotResource."),
            new Question("Give 2 JSON IAM policy fields that are optional.", "Id and Sid."),
            new Question("Which Route53 routing policy is active/passive?",
                    "Failover routing - primary is active and the other is on standby. Only if the primary fails the health check does traffic get routed into the failover instance."),
            new Question("What does Storage Gateway do and what is it useful for? (x4 points)",
                    "It bridges the on-prem data and cloud data; it helps with the push for hybrid cloud; you can use it to expose S3 data on-prem; it's good for disaster recovery, backup and storage, and tiered storage."),
            new Question("STS - 2 bullet points:",
                    "Create temporary, limited-priveleges credentials to access your AWS resources. Good for identity federation or IAM roles."),
            new Question("In EC2, what's the difference between reserved instances and capacity reservations?",
                    "Reserved instances are a billing discount comittment (best for steady-state usage); capacity reservations are for guaranteeing hardware availability in a specific AZ."),
            new Question("What are Lifecycle configurations?",
                    "Set them up to move things between S3 classes automatically, e.g. X days after creation move to X class."),
            new Question("What is Trusted Advisor?",
                    "High-level account assessment. Gives recommendations on cost optimisation, performance, security, fault tolerance, service limits, and operational excellence."),
            new Question("What are the 6 CAF perspectives?",
                    "Business, People, Governance, Platform, Security, Operations."),
            new Question("GuardDuty vs Inspector vs Detective?",
                    "GuardDuty is intelligent threat discovery; Inspector runs assessments on EC2 instances, container images and lambda ONLY; detective identifies root cause of security issues/suspicious activites."),
            new Question("What is SSM?", "Systems Manager - manage your fleet of EC2 instances."),
            new Question("CloudTrail vs Config?",
                    "CloudTrail records who made an API call when (it's trailing users); Config tracks how the configuration of a resource has changed over time and is good for compliance."),
            new Question("What is TCO?",
                    "Total Cost of Ownership - compare costs of running on-prem vs migrating to the cloud."),
            new Question("What is data sovereignty?",
                    "Digital data is subject to the laws and governance of the country where it is physically stored or processed."),
            new Question("What can check for the presence of SQL injection?", "WAF."),
            new Question("How would I connect multiple VPCs and on-prem systems?", "Transit Gateway."),
            new Question(
                    "What would I use to forecast costs of what I am already using, vs predict costs before making decisions?",
                    "Cost Explorer forecasts AWS usage and costs; Pricing Calculator is to estimate costs before making decisions."),
            new Question("Give an example of a schemaless database.", "DynamoDB."),
            new Question("Redshift - 4 bullet points:",
                    "Data warehouse; relational database; columnar; suited for OLAP."),
            new Question("What service provides static IP addresses that act as a fixed entry point to your apps?",
                    "Global Accelerator."),
            new Question("What are the 4 CAF transformation domains?",
                    "Technology, Process, Organisation, Product."),

            new Question("What can I use to move files from an on-prem NFS to EC2 instances in the cloud?",
                    "EFS"),
            new Question("What's the difference between DataSync and Storage Gateway?",
                    "DayaSync is for fast, bulk data migration and scheduled replication. Storage Gateway is persistent, on-prem storage extension for daily use."),
            new Question("What are the two types of Reserved Instance?", "Standard RI and Convertible RI."),
            new Question("Is data automatically encrypted between AZs?", "Yes."),
            new Question("What are access keys used for?",
                    "Making programmatic calls to AWS from AWS APIs"),
            new Question("What security credentials do I need to use the management console?",
                    "password + MFA"),
            new Question("What security credentials do I need to use the CLI?", "Access keys"),
            new Question("What security credentials do I need to use the SDK", "Access keys"),
            new Question("Cost of Elastic Beanstalk?", "Free - just pay for underlying resources."),
            new Question("Health monitoring in Elastic Beanstalk?",
                    "Full monitoring suite - each EC2 instance has a health agent that pushes metrics to CloudWatch."),
            new Question("What can Elastic Beanstalk be used for?", "Web apps and non-web apps."),
            new Question("What common 3-tier architecture does Elastic Beanstalk help with?",
                    "ELB + EC2 instances + DB (with ASG)."),
            new Question("What is a resource group?",
                    "A collection of AWS resources in the same region that match specific criteria, like shared tags or CloudFormation stack."),
            new Question("What are some use cases for a resource group?",
                    "Apps in different phases like dev/prod; projects managed by multiple departments; AWS resources used together or that you want to manage/monitor as a group."),
            new Question("What is the Operational Excellence pillar for?",
                    "Running, monitoring and continuously improving systems to deliver business value."),
            new Question("What is the performance efficiency pillar for?",
                    "Using resources efficiently, choosing right types, adapting to demands."),
            new Question("Where are EBS snapshots stored?", "S3."),
            new Question("What does a node (usually) refer to in AWS?", "An EC2 instance."),
            new Question(
                    "Where can you subscribe to an RSS feed to be notified of the status of all AWS service interruptions?",
                    "Health Dashboard - Service Health."),
            new Question("What is fault toelrance?",
                    "The ability of a system to keep working with no downtime or data loss if hardware/software breaks."),
            new Question("How is fault tolerance achieved in AWS (x3)?",
                    "AZs; making spare copies of data; switching to healthy parts automatically."),
            new Question("Name two things that can be used to host a SQL DB.", "RDS and EC2."),
            new Question("Name two things that can be used for the read/write of constantly changing data.",
                    "RDS and EFS."),
            new Question("What are two types of savings plan?",
                    "Compute savings plan and EC2 instance savings plan.") };
}
